spring.main.web-application-type=none
spring.main.banner-mode=off
logging.pattern.console=

spring.ai.mcp.server.name=streaming-datalakehouse-mcp
spring.ai.mcp.server.version=0.1.0

logging.file.name=~/streaming-lakehouse-mcp.log

trino.host=localhost
trino.port=8080
trino.user=admin
trino.catalog=semantic_demo
trino.schema=streaming_db

kafka.bootstrap.servers=localhost:29092
